config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'categories/new'

  get 'categories/create'

  get 'categories/update'

  get 'categories/edit'

  get 'categories/destroy'

  get 'categories/index'

  get 'categories/show'

  get 'posts/new'

  get 'posts/create'

  get 'posts/update'

  get 'posts/edit'

  get 'posts/destroy'

  get 'posts/index'

  get 'posts/show'

  get 'users/new'

  get 'users/create'

  get 'users/update'

  get 'users/edit'

  get 'users/destroy'

  get 'users/index'

  get 'users/show'

  get 'about/index'

  resources :posts
  resources :users
  resources :about
  resources :categories

  root 'about#index'

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index

    @title = 'Pisite o svemu'
    @category = Category.all
    @post = Post.all
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/views/about/index.html.erb
<h1><%= @title %></h1>

<p>glavni index The Ruby Racer is designed to let you evaluate JavaScript as safely as possible unless you tell it to do something more dangerous. The default context is a hermetically sealed JavaScript environment with only the standard JavaScript objects and functions. Nothing from the Ruby world is accessible at all.

  For Ruby objects that you explicitly embed into JavaScript, by default only the public methods below Object are exposed by default. E.g.</p>
<% if user_signed_in? %>

<% @post.each do |post| %>

<div class="col-md-4">
  <h2><%= post.title %></h2>
  <p>User: <%= link_to post.user.email, user_path(post.user.id) %> </p>
  <p>Category: <%= link_to post.category.name, category_path(post.category.id) %> </p>
  <p><%= link_to "View details >>", post_path(post.id), :class => "btn btn-default" %></p>
</div>
<% end %>
<% end %>